version: 2
template:
  name: Deploy OpenIDL Apps
  description: This toolchain allows to set initial parameters for all OpenIDL apps and build pipelines accordingly
  required:
    - hostedgit00
    - hostedgit06
    - hostedgit09
    - hostedgitutilities
    - hostedgitdatacallapp
    - ui
toolchain:
  name: openidl-apps-toolchain
services:
  hostedgitutilities:
    parameters:
      extra_capabilities:
        - capability_id: git.issues
          display_name: Issues
          dashboard_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-utilities/issues
          label: openidl-utilities
          tags:
            - think
            - code
          enabled: false
          readme: false
      label: openidl-utilities
      type: link
      git_id: hostedgit
      owner_id: openIDL
      repo_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-utilities.git
      private_repo: true
      has_issues: false
      enable_traceability: false
      authorized: hostedgit
      integration_owner: IBMid-06000238QN
      repo_name: openidl-utilities
      api_root_url: https://us-south.git.cloud.ibm.com/api
      token_url: https://otc-github-consolidated-broker.us-south.devops.cloud.ibm.com/github/token?git_id=hostedgit
      custom_host: ""
      namespace_table: ""
    service_id: hostedgit

  hostedgit00:
    parameters:
      extra_capabilities:
        - capability_id: git.issues
          display_name: Issues
          dashboard_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-transactional-data-event-listener/issues
          label: openidl-transactional-data-event-listener
          tags:
            - think
            - code
          enabled: false
          readme: false
      label: openidl-transactional-data-event-listener
      type: link
      git_id: hostedgit
      owner_id: openIDL
      repo_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-transactional-data-event-listener.git
      private_repo: true
      has_issues: false
      enable_traceability: false
      authorized: hostedgit
      integration_owner: IBMid-06000238QN
      repo_name: openidl-transactional-data-event-listener
      api_root_url: https://us-south.git.cloud.ibm.com/api
      token_url: https://otc-github-consolidated-broker.us-south.devops.cloud.ibm.com/github/token?git_id=hostedgit
    service_id: hostedgit
  ui:
    parameters:
      extra_capabilities:
        - capability_id: git.issues
          display_name: Issues
          dashboard_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-ui/issues
          label: openidl-ui
          tags:
            - think
            - code
          enabled: false
          readme: false
      label: openidl-ui
      type: link
      repo_name: openidl-ui
      repo_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-ui.git
      source_repo_url: https://github.com/open-toolchain/hello-containers
      has_issues: false
      enable_traceability: false
      git_id: hostedgit
      custom_host: ""
      namespace_table: ""
      owner_id: openIDL
      private_repo: true
      authorized: hostedgit
      integration_owner: IBMid-06000238QN
      api_root_url: https://us-south.git.cloud.ibm.com/api
      token_url: https://otc-github-consolidated-broker.us-south.devops.cloud.ibm.com/github/token?git_id=hostedgit
    service_id: hostedgit
  hostedgit09:
    parameters:
      extra_capabilities:
        - capability_id: git.issues
          display_name: Issues
          dashboard_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-chaincode/issues
          label: openidl-chaincode
          tags:
            - think
            - code
          enabled: false
          readme: false
      label: openidl-chaincode
      type: link
      git_id: hostedgit
      owner_id: openIDL
      repo_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-chaincode.git
      private_repo: true
      has_issues: false
      enable_traceability: false
      authorized: hostedgit
      integration_owner: IBMid-06000238QN
      repo_name: openidl-chaincode
      api_root_url: https://us-south.git.cloud.ibm.com/api
      token_url: https://otc-github-consolidated-broker.us-south.devops.cloud.ibm.com/github/token?git_id=hostedgit
      custom_host: ""
      namespace_table: ""
    service_id: hostedgit
  hostedgit06:
    parameters:
      extra_capabilities:
        - capability_id: git.issues
          display_name: Issues
          dashboard_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-data-call-mood-listener/issues
          label: openidl-data-call-mood-listener
          tags:
            - think
            - code
          enabled: false
          readme: false
      label: openidl-data-call-mood-listener
      type: link
      git_id: hostedgit
      owner_id: openIDL
      repo_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-data-call-mood-listener.git
      private_repo: true
      has_issues: false
      enable_traceability: false
      authorized: hostedgit
      integration_owner: IBMid-06000238QN
      repo_name: openidl-data-call-mood-listener
      api_root_url: https://us-south.git.cloud.ibm.com/api
      token_url: https://otc-github-consolidated-broker.us-south.devops.cloud.ibm.com/github/token?git_id=hostedgit
    service_id: hostedgit
  pipelinedatacallapp:
    parameters:
      label: data-call-app
      type: classic
      name: data-call-app
      ui_pipeline: true
      api_url: http://pipeline-service/pipeline/pipelines/5b015343-6db6-480d-aaee-cad48a42d2f5
      external_api_url: https://pipeline-service.us-south.devops.cloud.ibm.com/pipeline/pipelines/5b015343-6db6-480d-aaee-cad48a42d2f5
      configuration:
        content:
          $text: pipeline_pipelinedatacallapp.yml
        env:
          GITHUB_TOKEN: '{{form.pipeline.parameters.github_token}}'
          CLUSTER_NAME: '{{form.pipeline.parameters.cluster_name}}'
          HOST: '{{form.pipeline.parameters.host}}'
          CROSS_CHANNELS: '{{form.pipeline.parameters.cross_channels}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
        execute: false
      services:
        - hostedgitdatacallapp
    service_id: pipeline
  pipelinechaincode:
    parameters:
      label: chaincode
      type: classic
      name: chaincode
      ui_pipeline: true
      api_url: http://pipeline-service/pipeline/pipelines/5b015343-6db6-480d-aaee-cad48a42d2f5
      external_api_url: https://pipeline-service.us-south.devops.cloud.ibm.com/pipeline/pipelines/5b015343-6db6-480d-aaee-cad48a42d2f5
      configuration:
        content:
          $text: pipeline_pipelinechaincode.yml
        env:
          ADMIN_IDENTITY: '{{form.pipeline.parameters.admin_identity}}'
          CONNECTION_PROFILE: '{{form.pipeline.parameters.connection_profile}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          CC_VERSION: '{{form.pipeline.parameters.cc_version}}'
          HOST: '{{form.pipeline.parameters.host}}'

        execute: false          
      services:
        - hostedgit09
    service_id: pipeline
  hostedgitdatacallapp:
    parameters:
      extra_capabilities:
        - capability_id: git.issues
          display_name: Issues
          dashboard_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-data-call-app/issues
          label: openidl-data-call-app
          tags:
            - think
            - code
          enabled: false
          readme: false
      label: openidl-data-call-app
      type: link
      git_id: hostedgit
      owner_id: openIDL
      repo_url: https://us-south.git.cloud.ibm.com/openIDL/openidl-data-call-app.git
      private_repo: true
      has_issues: false
      enable_traceability: false
      authorized: hostedgit
      integration_owner: IBMid-06000238QN
      repo_name: openidl-data-call-app
      api_root_url: https://us-south.git.cloud.ibm.com/api
      token_url: https://otc-github-consolidated-broker.us-south.devops.cloud.ibm.com/github/token?git_id=hostedgit
      custom_host: ""
      namespace_table: ""
    service_id: hostedgit
  pipeline10:
    parameters:
      label: mood-listener
      type: classic
      name: mood-listener
      ui_pipeline: true
      api_url: http://pipeline-service/pipeline/pipelines/312a017b-76a7-4e1e-8b03-486617203596
      external_api_url: https://pipeline-service.us-south.devops.cloud.ibm.com/pipeline/pipelines/312a017b-76a7-4e1e-8b03-486617203596
      configuration:
        content:
          $text: pipeline_pipeline10.yml
        env:
          GITHUB_TOKEN: '{{form.pipeline.parameters.github_token}}'
          CLUSTER_NAME: '{{form.pipeline.parameters.cluster_name}}'
          MOOD_LISTENER_CHANNELS_EVENTS: '{{form.pipeline.parameters.mood_listener_channels_events}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
        execute: false                    
      services:
        - hostedgit06
    service_id: pipeline
  pipeline13:
    parameters:
      label: data-transaction-listener
      type: classic
      name: data-transaction-listener
      ui_pipeline: true
      api_url: http://pipeline-service/pipeline/pipelines/d34a632d-3d1a-4685-a17d-abe47a5d82f8
      external_api_url: https://pipeline-service.us-south.devops.cloud.ibm.com/pipeline/pipelines/d34a632d-3d1a-4685-a17d-abe47a5d82f8
      configuration:
        content:
          $text: pipeline_pipeline13.yml
        env:
          GITHUB_TOKEN: '{{form.pipeline.parameters.github_token}}'
          CLUSTER_NAME: '{{form.pipeline.parameters.cluster_name}}'
          DATA_LISTENER_CHANNELS_EVENTS: '{{form.pipeline.parameters.data_listener_channels_events}}'
          TARGET_CHANNELS: '{{form.pipeline.parameters.target_channels}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
        execute: false          
      services:
        - hostedgit00
    service_id: pipeline
  build:
    parameters:
      label: openidl-ui
      type: classic
      name: openidl-ui
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline_build.yml
        env:
          GITHUB_TOKEN: '{{form.pipeline.parameters.github_token}}'
          CLUSTER_NAME: '{{form.pipeline.parameters.cluster_name}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          DATA_CALL_APP_URL: https://openidl-data-call-app.{{form.pipeline.parameters.cluster_name}}.us-east.containers.appdomain.cloud/openidl/api
        execute: false
      ui_pipeline: true
      api_url: http://pipeline-service/pipeline/pipelines/acbdeeae-2605-4fa3-9149-5ce3283fe8b1
      external_api_url: https://pipeline-service.us-south.devops.cloud.ibm.com/pipeline/pipelines/acbdeeae-2605-4fa3-9149-5ce3283fe8b1
      services:
        - ui
    service_id: pipeline
  pipeline17:
    parameters:
      label: openidl-utilities
      type: classic
      name: openidl-utilities
      ui_pipeline: true
      api_url: http://pipeline-service/pipeline/pipelines/b4e691cf-5dba-411b-94b7-03467e0d8f66
      external_api_url: https://pipeline-service.us-south.devops.cloud.ibm.com/pipeline/pipelines/b4e691cf-5dba-411b-94b7-03467e0d8f66
      configuration:
        content:
          $text: pipeline_pipeline17.yml
        env:
          GITHUB_TOKEN: '{{form.pipeline.parameters.github_token}}'
          HOST: '{{form.pipeline.parameters.host}}'
          CLUSTER_NAME: '{{form.pipeline.parameters.cluster_name}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
        execute: false          
      services:
        - hostedgitutilities
    service_id: pipeline
    
form:
  pipeline:
    schema:
      $ref: deploy.json
