- hosts: ansible_provisioners
  gather_facts: yes
  no_log: "{{ no_ansible_log | default(false) }}"
  vars_files:
    - "./{{ org_name }}-config-{{ env }}.yml"

  tasks:
    - include_role:
        name: "prepare"
      vars:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        aws_external_id: "{{ aws_external_id }}"
        aws_iam_role: "{{ aws_iam_role }}"
      when: deploy_action == "applications"

    - include_role:
        name: apps
      vars:
        app_cluster_name: "{{ app_cluster_name }}"
        aws_region: "{{ aws_region }}"
        gitrepo_name: "{{ gitrepo_name }}"
        gitepo_branch: "{{ gitrepo_branch }}"
        gitrepo_username: "{{ gitrepo_username }}"
        gitrepo_password: "{{ gitrepo_password }}"


