---
- name: Update kubeconfig and set context to openidl {{ app_cluster_name }}
  shell: |
    export AWS_PROFILE=cicd-role; aws eks update-kubeconfig --region {{ aws_region }} --name {{ app_cluster_name }}

- name: Download git repository content
  git:
    repo: "https://{{gitrepo_username|urlencode()}}:{{gitrepo_password|urlencode()}}@{{ gitrepo_name }}"
    dest: /tmp/openidl
    force: yes
    single_branch: yes
    version: "{{ gitrepo_branch }}"

- name: Deploy openIDL app using helm
  shell: |
    helm upgrade --recreate-pods --install dev-carrier /tmp/openidl/openidl-k8s -f /tmp/openidl/openidl-k8s/global-values-{{ env }}-{{ node_type }}.yaml \
      -n openidl --set global.datacallapp.ingressenabled=true --set global.utilities.ingressenabled=true \
      --set global.carrierui.ingressenabled=true --set global.insurancedatamanager.ingressenabled=true \
      --set global.secrets.install=false

- name: Dispose temporary git repository content
  file:
    path: /tmp/openidl/
    state: absent
