#GitHub Actions to deploy secrets
#It requires the EKS cluster public access turned ON

#Prerequisites:
# IAM user (access key and secret key) and IAM role setup to gain access to EKS cluster
# AWS Region of EKS cluster and Secret Manager configured (note: Both will be same region)
# EKS Cluster name
# Name of the Secret in AWS secret maanger setup
# Setup the following secrets in github as environment secrets under environment named "dev-aais"
# 1. eks_admin_access_key
# 2. eks_admin_secret_key
# 3. eks_admin_role
# 4. eks_external_id
# 4. eks_sm_region (The AWS region of EKS and Secret Manager)
# 5. eks_cluster_name
# 6. vault_secret_name (name of the secret setup in vault to retrieve credentials)

# Authors: Rajesh Sanjeevi & Sandeep Pulluru
# Version: 1.0

name: Deploy openIDL dev-aais-secrets
on:
  push:
    branches:
      - 'mood-listener'
    paths:
#      - 'openidl-k8s/global-values-secrets.yaml'

defaults:
  run:
    shell: bash

jobs:
  secrets-dev-aais:
  #  environment: dev-aais
    name: Deploy openIDL secrets on dev-aais
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Configure AWS CLI with credentials
      uses: aws-actions/configure-aws-credentials@230d25f14e841bc8e06b5f4ff89ccd6989fc1d71
      with:
        aws-access-key-id: ${{ secrets.eks_admin_access_key }}
        aws-secret-access-key: ${{ secrets.eks_admin_secret_key }}
        aws-region: ${{ secrets.eks_sm_region }}
        role-to-assume: ${{ secrets.eks_admin_role }}
        role-external-id: ${{ secrets.eks_external_id }}
        role-duration-seconds: 3600 # session valid for 30 minutes
        role-session-name: git-actions

    - name: Update kube-config for eks cluster
      run: |
       aws eks update-kubeconfig --region ${{ secrets.eks_sm_region }} --name ${{ secrets.eks_cluster_name }}

    - name: Prepare a pod
      run: |
        kubectl run deploy-secrets -n openidl --image=amazonlinux:latest --command sleep infinity
        sleep 60
        kubectl exec deploy-secrets -n openidl -- sh -c "yum install tar -y > /dev/null 2&>1"
        kubectl cp openidl-k8s/ openidl/deploy-secrets:/
        kubectl cp openidl-test-network/vault/ openidl/deploy-secrets:/
        kubectl exec deploy-secrets -n openidl -- sh -c "chmod +x vault/*.sh"
        kubectl exec deploy-secrets -n openidl -- sh -c "mkdir openidl-k8s/charts/openidl-secrets/config-dev-aais"
        kubectl exec deploy-secrets -n openidl -- sh -c "./vault/deploy-utilities.sh -a ${{ secrets.eks_admin_access_key }} -s ${{ secrets.eks_admin_secret_key }} -r ${{ secrets.eks_sm_region }} -o ${{ secrets.eks_admin_role }}"

    - name: Retrive secrets from vault
      run: |
        kubectl exec deploy-secrets -n openidl -- sh -c "./vault/pull-aws-vault-config.sh -s ${{ secrets.vault_secret_name }} -r ${{ secrets.eks_sm_region }} -a config-aais -c openidl-k8s/charts/openidl-secrets/config-dev-aais"

    - name: Deploy secrets
      run: |
        kubectl exec deploy-secrets -n openidl -- sh -c "export AWS_PROFILE=git-role; aws eks update-kubeconfig --region ${{ secrets.eks_sm_region }} --name ${{ secrets.eks_cluster_name }}"
        kubectl exec deploy-secrets -n openidl -- helm version
    #    kubectl exec deploy-secrets -n openidl -- helm upgrade --install dev-aais-secrets ./openidl-k8s -f ./openidl-k8s/global-values-secrets.yaml -n openidl --set global.configpath=config-dev-aais

    - name: Dispose the pod
      if: ${{ always() }}
      run: |
        kubectl delete pod deploy-secrets -n openidl