name: Manual triggered workflow - Deploy openidl app-v1.0
on:
  workflow_dispatch:
    inputs:
      node_type:
        description: "Node type (aais|analytics|carrier)"
        required: true
        default: ""
      env:
        description: "Environment Type (dev|test|prod)"
        required: true
        default: ""
      eks_region:
        description: "AWS region of EKS cluster"
        required: true
        default: ""
      eks_cluster_name:
        description: "EKS cluster name"
        required: true
        default: ""

defaults:
  run:
    shell: bash
    #working-directory: openidl-k8s

jobs:
  deploy-openidl-app-aais:
    #environment: aais_dev

    if: ${{ github.event.inputs.node_type }} == 'aais' && ${{ github.event.inputs.env }} == 'dev'
    name: Deploy openidl application for node AAIS in DEV
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS CLI with credentials
      uses: aws-actions/configure-aws-credentials@230d25f14e841bc8e06b5f4ff89ccd6989fc1d71
      with:
        aws-access-key-id: ${{ secrets.aais_access_key}}
        aws-secret-access-key: ${{ secrets.aais_secret_key }}
        aws-region: ${{ github.event.inputs.eks_region }}
        role-to-assume: ${{ secrets.aais_role }}
        role-external-id: aais-terraform
        role-duration-seconds: 3600 # session valid for 30 minutes
        role-session-name: GitHubActions

    - name: Checkout Code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.6.3

    - name: Setup kube-config
      run: |
        aws eks update-kubeconfig --region ${{ github.event.inputs.eks_region }} --name ${{ github.event.inputs.eks_cluster_name }}
    - name: Helm upgrade
      run: |
        helm upgrade dev-aais ./openidl-k8s -f ./openidl-k8s/global-values-aais.yaml -n openidl --set global.datacallapp.ingressenabled=true --set global.utilities.ingressenabled=true --set global.ui.ingressenabled=true --set global.insurancedatamanager.ingressenabled=true --set global.configpath=config-aais-dev
