#For the workflow to function, the following prerequisites are required to setup.
#1) AWS IAM user having access to EKS cluster
#2) AWS IAM User access key and secret key
#3) AWS region of the EKS cluster resource
#4) EKS Cluster name
#5) AWS region of the AWS secrets manager service
#6) Name of the secret to retrieve from AWS secrets manager service
#7) Setup Github environment and use naming standard as <node-type>-<env-type> (Ex: aais-dev|aais-test|aais-prod|analytics-dev|analytics-test|analytics-prod|carrier-dev|carrier-test|carrier|prod)
#8) Setup the following environment secrets under environment setup in #7
#     eks_admin_access_key
#     eks_admin_secret_key
#     eks_region
#     eks_cluster_name
#     secretmanager_region
#     secret_name

name: Deploy secrets v1.0
on:
  push:
#    branches:
#      - 'mood-listener'
#  # paths:
  #    - ''

defaults:
  run:
    shell: bash

jobs:
  secrets-aais-dev:
  #  environment: aais-dev
  #  requires a condition to trigger relevant job
    name: Deploy secrets for aais node in DEV
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Configure AWS CLI with credentials
      uses: aws-actions/configure-aws-credentials@230d25f14e841bc8e06b5f4ff89ccd6989fc1d71
      with:
        aws-access-key-id: ${{ secrets.eks_admin_access_key }}
        aws-secret-access-key: ${{ secrets.eks_admin_secret_key }}
        aws-region: ${{ secrets.eks_region }}
      # role-to-assume: ${{ secrets.eks_admin_role }}
      # role-external-id: ${{ secrets.eks_external_id }}
      # role-duration-seconds: 3600 # session valid for 30 minutes
      # role-session-name: GitHubActions-session

    - name: Update kube-config for eks cluster
      run: |
       aws eks update-kubeconfig --region ${{ secrets.eks_region }} --name ${{ secrets.eks_cluster_name }}

    - name: Prepare a pod
      run: |
        kubectl run deploy-secrets -n openidl --image=amazonlinux:latest --command sleep infinity
        sleep 60
        kubectl exec deploy-secrets -n openidl -- sh -c "yum install tar -y > /dev/null 2&>1"
        kubectl cp openidl-k8s/ openidl/deploy-secrets:/
        kubectl cp openidl-test-network/vault/ openidl/deploy-secrets:/
        kubectl exec deploy-secrets -n openidl -- sh -c "chmod +x vault/*.sh; mkdir openidl-k8s/charts/openidl-secrets/config-aais-dev"
  #      kubectl exec deploy-secrets -n openidl -- sh -c "mkdir openidl-k8s/charts/openidl-secrets/config-aais-dev"
        kubectl exec deploy-secrets -n openidl -- sh -c "./vault/deploy-utilities.sh -a ${{ secrets.eks_admin_access_key }} -s ${{ secrets.eks_admin_secret_key }} -r ${{ secrets.eks_region }}"

    - name: Retrive secrets from vault
      run: |
        kubectl exec deploy-secrets -n openidl -- sh -c "./vault/pull-awssm-vault.sh -s ${{ secrets.secret_name }} -r ${{ secrets.secretmanager_region }} -a config-aais -c openidl-k8s/charts/openidl-secrets/config-aais-dev"

    - name: Deploy secrets
      run: |
        kubectl exec deploy-secrets -n openidl -- aws eks update-kubeconfig --region ${{ secrets.eks_region }} --name ${{ secrets.eks_cluster_name }}
        kubectl exec deploy-secrets -n openidl -- helm upgrade --install dev-aais-secrets ./openidl-k8s -f ./openidl-k8s/global-values-secrets.yaml -n openidl --set global.configpath=config-aais-dev

    - name: Dispose the pod
      if: ${{ always() }}
      run: |
        kubectl delete pod deploy-secrets -n openidl

