#To enable this workflow, below secrets are required to setup in environment aais_dev
#1. eks_admin_access_key
#2. eks_admin_secret_key
#3. eks_region
#4. eks_cluster_name
#5. secretmanager_region
#6. secret_name

name: Deploy secrets v1.0
on:
  push:
    branches:
      - 'mood-listener'
  # paths:
  #    - ''

defaults:
  run:
    shell: bash
  # working-directory:

jobs:
  secrets-aais-dev:
  #  environment: aais-dev

    name: Deploy secrets for aais node in DEV
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Configure AWS CLI with credentials
      uses: aws-actions/configure-aws-credentials@230d25f14e841bc8e06b5f4ff89ccd6989fc1d71
      with:
        aws-access-key-id: ${{ secrets.eks_admin_access_key }}
        aws-secret-access-key: ${{ secrets.eks_admin_secret_key }}
        aws-region: ${{ secrets.eks_region }}
      # role-to-assume: ${{ secrets.eks_admin_role }}
      # role-external-id: ${{ secrets.eks_external_id }}
      # role-duration-seconds: 3600 # session valid for 30 minutes
      # role-session-name: GitHubActions-session

    - name: Update kube-config for eks cluster
      run: |
       aws eks update-kubeconfig --region ${{ secrets.eks_region }} --name ${{ secrets.eks_cluster_name }}

    - name: Prepare a pod
      run: |
        kubectl run deploy-secrets -n openidl --image=amazonlinux:latest --command sleep infinity
        sleep 60

        kubectl cp openidl-k8s/ openidl/deploy-secrets:/
        kubectl cp openidl-test-network/ openidl/deploy-secrets:/

        kubectl exec deploy-secrets -n openidl -- chmod +x openidl-test-network/vault/*.sh
        kubectl exec deploy-secrets -n openidl -- mkdir openidl-k8s/charts/openidl-secrets/config-aais-dev
        kubectl exec deploy-secrets -n openidl -- sh -c "./openidl-test-network/vault/deploy-utilities.sh -a ${{ secrets.eks_admin_access_key }} -s ${{ secrets.eks_admin_secret_key }} -r ${{ secrets.eks_region }}


    - name: Retrive secrets from vault
      run: |
        kubectl exec deploy-secrets -n openidl -- sh -c "./openidl-test-network/vault/pull-awssm-vault.sh -s ${{ secrets.secret_name }} -a config-aais-dev -c openidl-k8s/charts/openidl-secrets/config-aais-dev"

    - name: Deploy secrets
      run: |
        kubectl exec deploy-secrets -n openidl -- helm upgrade --install dev-aais-secrets ./openidl-k8s -f ./openidl-k8s/global-values-secrets.yaml -n openidl  --set global.configpath=config-aais-dev

    - name: Dispose the pod
      if: ${{ always() }}
      run: |
      #  kubectl delete pod deploy-secrets -n openidl

