name: Publish openIDL ui and carrier-ui
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'openidl-ui-workspace/**'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  IMAGE_NAME: openidl

defaults:
  run:
    shell: bash
    working-directory: openidl-ui-workspace

jobs:
  build-and-push-image-ui-workspace:
    name: Build and Push - openIDL ui and carrier-ui to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Log into GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Prepare .npmrc
        id: npmrc
        run: |
          sed -i 's|${GITHUB_TOKEN}|${{ secrets.GITHUB_TOKEN }}|' ./.npmrc

      - name: Get Current Date and Time
        id: datetime
        run: echo "BUILD_DATETIME=$(date +%m%d%Y%H%M)" >> ${GITHUB_ENV}

      - name: Get Branch Name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}

      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA")" >> ${GITHUB_ENV}

      - name: Build and Push Docker Image for openidl-ui (aais)
        uses: docker/build-push-action@v2
        with:
          context: openidl-ui-workspace
          build-args: PROJECT=aais
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/openidl-org/${{ env.IMAGE_NAME }}-ui:latest
            ${{ env.REGISTRY }}/openidl-org/${{ env.IMAGE_NAME }}-ui:${{ github.run_number }}-${{ env.BRANCH }}-${{ env.COMMIT_ID }}-${{ env.BUILD_DATETIME }}

      - name: Build and Push Docker Image for openidl-carrier-ui (carrier)
        uses: docker/build-push-action@v2
        with:
          context: openidl-ui-workspace
          build-args: PROJECT=carrier
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-carrier-ui:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-carrier-ui:${{ github.run_number }}-${{ env.BRANCH }}-${{ env.COMMIT_ID }}-${{ env.BUILD_DATETIME }}


