name: Publish openidl insurance-data-manager-v1.0
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'openidl-insurance-data-manager/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openidl-insurance-data-manager
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: $${{ secrets.ACCESS_TOKEN }}

defaults:
  run:
    shell: bash
    working-directory: openidl-insurance-data-manager

jobs:
  build-and-push-image-insurance-data-manager:
    name: Build and Push - openIDL insurance-data-manager to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Log into GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Prepare .npmrc
        id: npmrc
        run: |
          sed -i 's|${GITHUB_TOKEN}|${{ secrets.ACCESS_TOKEN }}|' ./.npmrc

      - name: Build Date&Time
        id: datetime
        run: echo "BUILD_DATETIME=$(date +%m%d%Y%H%M)" >> ${GITHUB_ENV}

      - name: Check branch-name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}

      - name: Check commit-id
        run: echo "COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA")" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: openidl-insurance-data-manager
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}-${{ env.BRANCH }}-${{ env.COMMIT_ID }}-${{ env.BUILD_DATETIME }}


