name: Publish Mapper
on:
  push:
    paths:
    - 'openidl-mapper/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: install
        run: npm install
        working-directory: openidl-mapper
      - name: publish
        run: npm publish --access public
        working-directory: openidl-mapper
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CONTAINER_TOKEN }}