name: Publish openidl ui-workspace-v1.0
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'openidl-ui-workspace/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openidl-ui-workspace
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: $${{ secrets.ACCESS_TOKEN }}

defaults:
  run:
    shell: bash
    working-directory: openidl-ui-workspace

jobs:
  build-and-push-image-ui-workspace:
    name: Build and Push - openIDL ui-workspace to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Log into GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Prepare .npmrc
        id: npmrc
        run: |
          sed -i 's|${GITHUB_TOKEN}|${{ secrets.ACCESS_TOKEN }}|' ./.npmrc

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        build-args: |
          PROJECT=aais
        with:
          context: openidl-ui-workspace
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
